version: "3"

volumes:
  keskne-logs:
  keskne-postgres:
  mbta-static:
  mbta-logs:
  rps-static:
  rps-logs:

services:
  # ===== Keskne =====
  revproxy:
    image: lucaspickering/keskne-revproxy:latest
    restart: always
    depends_on:
      - wordpress
      - mbta-api
      - mbta-static
      - rps-api
      - rps-static
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/app/certs:ro
      - keskne-logs:/var/log/nginx:rw
      - mbta-static:/app/mbta:ro
      - rps-static:/app/rps:ro

  postgres:
    image: lucaspickering/keskne-postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD
      - MBTA_DB
      - MBTA_DB_PASSWORD
      - RPS_DB
      - RPS_DB_PASSWORD
    volumes:
      - keskne-postgres:/var/lib/postgresql/data:rw

  # ===== Wordpress =====
  wordpress-db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - /var/lp.me/wordpress-db:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - wordpress-db
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - /var/lp.me/wordpress:/var/www/html:rw

  # ===== MBTA =====
  # WARNING: Django rejects all requests if your hostname has an underscore!
  mbta-api:
    image: lucaspickering/mbta-api:latest
    restart: always
    environment:
      - MBTA_DB_HOST=postgres
      - MBTA_DB_NAME=${MBTA_DB}
      - MBTA_DB_USER=${MBTA_DB}
      - MBTA_DB_PASSWORD
      - MBTA_SECRET_KEY
    depends_on:
      - postgres
    volumes:
      - mbta-logs:/var/log/gunicorn:rw

  mbta-static:
    image: lucaspickering/mbta-static:latest
    volumes:
      - mbta-static:/app/static:rw

  # ===== RPS =====
  rps-redis:
    image: redis:5-alpine
    restart: always

  rps-api:
    image: lucaspickering/rps-api:latest
    restart: always
    environment:
      - RPS_REDIS_HOST=rps-redis:6379
      - RPS_DB_HOST=postgres
      - RPS_DB_NAME=${RPS_DB}
      - RPS_DB_USER=${RPS_DB}
      - RPS_DB_PASSWORD
      - RPS_SECRET_KEY
    depends_on:
      - postgres
    volumes:
      - rps-logs:/var/log/daphne:rw

  rps-static:
    image: lucaspickering/rps-static:latest
    volumes:
      - rps-static:/app/static:rw
