version: "3"

services:
  revproxy:
    build: ./revproxy
    image: ghcr.io/lucaspickering/keskne-revproxy:${KESKNE_IMAGE_TAG}

  db-backup:
    build: ./db-backup
    image: ghcr.io/lucaspickering/keskne-db-backup:${KESKNE_IMAGE_TAG}
