version: "3"

volumes:
  keskne-logs:
  mbta-static:
  mbta-logs:

services:
  revproxy:
    build: .
    image: keskne
    restart: always
    depends_on:
      - wordpress
      - mbta-api
      - mbta-static
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/app/certs:ro
      - keskne-logs:/var/log/nginx:rw
      - mbta-static:/app/mbta:ro

  # ===== Wordpress =====
  wordpress-db:
    image: mysql:5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - /var/lp.me/wordpress-db:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on:
      - wordpress-db
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - /var/lp.me/wordpress:/var/www/html:rw

  # ===== MBTA =====
  mbta-db:
    image: lucaspickering/mbta-db:latest
    restart: always
    environment:
      - POSTGRES_DB=mbta
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/app/postgres

  # WARNING: Django rejects all requests if your hostname has an underscore!
  mbta-api:
    image: lucaspickering/mbta-api:latest
    restart: always
    environment:
      - DB_HOSTNAME=mbta-db
      - DB_PASSWORD=root
    depends_on:
      - mbta-db
    volumes:
      - mbta-logs:/var/log/gunicorn:rw

  mbta-static:
    image: lucaspickering/mbta-static:latest
    volumes:
      - mbta-static:/app/static:rw
