version: "3"

volumes:
  keskne-postgres:
  keskne-logs:
  mbta-logs:
  rps-logs:

services:
  # ===== Keskne =====
  revproxy:
    image: lucaspickering/keskne-revproxy:latest
    depends_on:
      - wordpress
      - mbta-api
      - rps-api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/app/certs:ro
      - keskne-logs:/var/log/nginx:rw
    deploy:
      restart_policy:
        condition: any

  postgres:
    image: lucaspickering/keskne-postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD
      - MBTA_DB=mbta
      - MBTA_DB_PASSWORD=mbta
      - RPS_DB=rps
      - RPS_DB_PASSWORD=rps
    volumes:
      - keskne-postgres:/var/lib/postgresql/data:rw
    deploy:
      restart_policy:
        condition: any

  # ===== Wordpress =====
  wordpress-db:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
    volumes:
      - /var/lp.me/wordpress-db:/var/lib/mysql
    deploy:
      restart_policy:
        condition: any

  wordpress:
    image: wordpress:latest
    depends_on:
      - wordpress-db
    environment:
      WORDPRESS_DB_HOST: wordpress-db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: root
    volumes:
      - /var/lp.me/wordpress:/var/www/html:rw
    deploy:
      restart_policy:
        condition: any

  # ===== MBTA =====
  # WARNING: Django rejects all requests if your hostname has an underscore!
  mbta-api:
    image: lucaspickering/mbta-api:latest
    environment:
      - MBTA_DB_HOST=postgres
      - MBTA_DB_NAME=mbta
      - MBTA_DB_USER=mbta
      - MBTA_DB_PASSWORD=mbta # TODO
      - MBTA_SECRET_KEY=mbta # TODO
    depends_on:
      - postgres
    volumes:
      - mbta-logs:/var/log/gunicorn:rw
    deploy:
      restart_policy:
        condition: any

  # ===== RPS =====
  rps-redis:
    image: redis:5-alpine
    deploy:
      restart_policy:
        condition: any

  rps-api:
    image: lucaspickering/rps-api:latest
    environment:
      - RPS_REDIS_HOST=rps-redis:6379
      - RPS_DB_HOST=postgres
      - RPS_DB_NAME=rps
      - RPS_DB_USER=rps
      - RPS_DB_PASSWORD=rps # TODO
      - RPS_SECRET_KEY=rps # TODO
    depends_on:
      - postgres
      - rps-redis
    volumes:
      - rps-logs:/var/log/daphne:rw
    deploy:
      restart_policy:
        condition: any
