name: Build and push images

on:
  push:
    branches:
      - master

jobs:
  build-all:
    name: "Build & push all images"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image_name: db-backup
            context: ./db-backup
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.context }}
          # `latest` tag is convenient to have, and also lets us download
          # the cache from a previous build
          tags: |
            ghcr.io/lucaspickering/${{ matrix.image_name }}:latest
            ghcr.io/lucaspickering/${{ matrix.image_name }}:${{ github.sha }}
          push: ${{ github.ref == 'refs/heads/master' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
