name: Build and push images

on:
  push:
    branches:
      - master

env:
  COMPOSE_FILE: docker-compose.build.yml

jobs:
  build-all:
    name: "Build & push all images"
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          pip install docker pyyaml
      - name: Docker login
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push images
        run: ./x.py build --push
